[tool]
id = "wsdl"

[[dependency]]
path = "../wsdl-cli/build/libs/wsdl-cli-@toml.version@.jar"

[[dependency]]
path = "../wsdl-core/build/libs/wsdl-core-@toml.version@.jar"

[[dependency]]
path = "lib/xsd-core-1.0.2.jar"

[[dependency]]
path = "lib/wsdl4j-@wsdl4j-version@.jar"

[[dependency]]
path = "lib/XmlSchema-@xmlschema-version@.jar"
